# Generated by Django 4.0 on 2021-12-09 21:39

from django.db import migrations, models
import utilities.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=utilities.helpers.generate_id, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('body', models.TextField(verbose_name='body')),
                ('status', models.CharField(choices=[('READ', 'READ'), ('SEND', 'SEND')], default='SEND', max_length=50, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
