# Generated by Django 4.0 on 2021-12-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='room'),
        ),
    ]
