# Generated by Django 4.0 on 2021-12-09 23:14

from django.db import migrations, models
import utilities.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.IntegerField(default=utilities.helpers.generate_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
